name: Build and Test

on:
  push:
    branches: [ TESTING ]
  pull_request:
    branches: [ TESTING ]

jobs:
  rootless-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64]  # match the matrix
    steps:
      - uses: actions/checkout@v4
      - name: Configure LOCAL_PREFIX
        run: |
          # Use current working directory to avoid permission issues
          export LOCAL_PREFIX="$(pwd)/local"
          mkdir -p "$LOCAL_PREFIX"
          echo "LOCAL_PREFIX=$LOCAL_PREFIX" >> $GITHUB_ENV
          echo "PATH=$LOCAL_PREFIX/usr/bin:$PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/lib:$LOCAL_PREFIX/usr/lib:$LOCAL_PREFIX/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib:$LOCAL_PREFIX/usr/lib/pkgconfig:$LOCAL_PREFIX/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "LOCAL_PREFIX set to $LOCAL_PREFIX"
          
      - name: Install dependencies (rootless)
        run: |
          echo "Running rootless on architecture: ${{ matrix.arch }}"
          bash scripts/linux/Piro_requirements_run_rootless.sh
          sudo apt-get install pocl-opencl-icd -y
          
      - name: Setup devices
        run: |
          ./scripts/linux/PIRO_devices_LIN
          clinfo

      - name: Build and test
        run: bash ./maketest.sh -d 0 -p 0
  
  rootful-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64]  # add architectures here
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (rootful)
        run: |
          echo "Running on architecture: ${{ matrix.arch }}"
          sudo apt-get update
          sudo scripts/linux/Piro_requirements_run_rootful.sh

      - name: Setup devices
        run: ./scripts/linux/PIRO_devices_LIN

      - name: Build and test
        run: bash ./maketest.sh -d 0 -p 0