name: Building

on:
  push:
    branches: [ TESTING ]
  pull_request:
    branches: [ TESTING ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo scripts/linux/Piro_requirements_run_rootful.sh
          ./scripts/linux/PIRO_devices_LIN
          bash ./maketest.sh -d 0 -p 0