name: Update README with PR info

on:
  push:
    branches:
      - main   # Trigger when there's a push to the main branch
  schedule:
    - cron: "0 0 * * *" # Optional: Run the workflow daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git user identity
        run: |
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git config --global user.name "${GITHUB_ACTOR}"

      - name: Get the latest Pull Request Number
        id: pr_number
        run: |
            PR_RESPONSE=$(curl -H "Authorization: token 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" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")
            echo "PR Response: $PR_RESPONSE"  # Debugging line

            # Check if there are any open PRs
            if [ "$(echo $PR_RESPONSE | jq length)" -gt 0 ]; then
            PR_NUMBER=$(echo $PR_RESPONSE | jq '.[0].number')
            echo "::set-output name=pr_number::$PR_NUMBER"
            else
            echo "No open pull requests found."
            echo "::set-output name=pr_number::none"
            fi
      
      - name: Update README with PR Number
        run: |
          PR_NUMBER=${{ steps.pr_number.outputs.pr_number }}
          echo "Latest Open Pull Request: #$PR_NUMBER" > README.md  # You can modify this to add content to the right part of your README
          git add README.md
          git commit -m "Update README with latest PR number"
          git push https://x-access-token:${{ secrets.FINE_GRAINED_TOKEN }}@github.com/${{ github.repository }}.git
